### ISSUE TITLE
Example for combined reading on Raspberry Pi?

### ISSUE THREAD

**Issue by syr** [sparkfun/Qwiic_BME280_CCS811_Combo#9]
I'm a bloody beginner. So it would be helpful to see in an example 
how to do combined readings with python which can be executed on a raspberry pi. :)
Any chance?

**Comment by nseidle** [comment]
We'd welcome a PR on either of the sensor libraries ([CCS811](https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library/) or [BME280](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/)) from anyone who want to contribute but most of our support is for Arduino instead of RPi/python.
